apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Production Test
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: ProdEnv
          artifact-id: e8679b45-968c-4127-869b-55222fe38ddf
          target-environment: ProdEnv