apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: QA1
          artifact-id: 54762bc1-e872-41f9-bf09-c6a64ae3cb33
          target-environment: QA